version: '3'
services:
  pgerupe:
    build: Database/
    image: docker.io/kane21/pgerupe:9.1
    container_name: pgerupe
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - dberupe:/var/lib/postgresql/data
    networks:
      - erupe
    configs:
      domainname: "pgerupe"

  srverupe:
    build: Server/
    image: docker.io/kane21/srverupe:9.1
    container_name: srverupe
    ports:
      - "53310:53310/tcp"
      - "53312:53312/tcp"
      - "54001:54001/tcp"
      - "54002:54002/tcp"
      - "54003:54003/tcp"
      - "54004:54004/tcp"
      - "54005:54005/tcp"
      - "54006:54006/tcp"
      - "54007:54007/tcp"
      - "54008:54008/tcp"
    volumes:
      - type: bind
        source: /mnt/d/erupe-bin
        target: /app/bin
      - type: bind
        source: /mnt/d/tmp
        target: /app/savedata
    networks:
      - erupe

volumes:
  dberupe:

networks:
  erupe: {}
